-- Test-chain parity for admin/drizzle/0003_identity_auto_approve.sql.
--
-- The live schema is applied by admin/scripts/migrate.ts from admin/drizzle/.
-- This chain is applied only by runMigrations (src/migrations.ts), which nothing
-- calls at runtime — its one consumer is test/database.integration.test.ts.
-- Because src/access-service.ts now reads users.auto_approve, the column has to
-- exist here too or the integration suite runs against a schema the code no
-- longer matches.
--
-- The last_verified_at backfill is deliberately absent: it corrects historical
-- production rows, and a freshly migrated test database has none.
ALTER TABLE users ADD COLUMN auto_approve boolean NOT NULL DEFAULT false;
