-- A source may now be created by a human administrator from the browser, so
-- `created_by` — a foreign key to the agent `users` table — is no longer
-- required. Mirrors 0006, which did the same for source_revisions.
--
-- Unlike 0006 this carries no retrieval risk: nothing in the MCP server inner
-- joins `users` on `sources.created_by`, so a null cannot silently drop a
-- source from search the way it would have on the revision side.
--
-- Only the nullability change belongs here. `created_by_admin_id` references
-- better-auth's "user" table, which this chain has no concept of; it ships in
-- admin/drizzle alone. See AGENTS.md.
ALTER TABLE sources ALTER COLUMN created_by DROP NOT NULL;
