/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as InviteTokenRouteImport } from './app/invite.$token'
import { Route as WSlugRouteImport } from './app/w/$slug'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as WSlugActivityRouteImport } from './app/w/$slug/activity'
import { Route as WSlugIdentitiesRouteImport } from './app/w/$slug/identities'
import { Route as WSlugPeopleRouteImport } from './app/w/$slug/people'
import { Route as WSlugReviewRouteImport } from './app/w/$slug/review'
import { Route as WSlugSettingsRouteImport } from './app/w/$slug/settings'
import { Route as WSlugSourcesRouteImport } from './app/w/$slug/sources'
import { Route as WSlugIdentitiesIndexRouteImport } from './app/w/$slug/identities/index'
import { Route as WSlugIdentitiesIdentityIdRouteImport } from './app/w/$slug/identities/$identityId'
import { Route as WSlugSourcesIndexRouteImport } from './app/w/$slug/sources/index'
import { Route as WSlugSourcesSourceIdRouteImport } from './app/w/$slug/sources/$sourceId'
import { Route as WSlugSourcesNewRouteImport } from './app/w/$slug/sources/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugActivityRoute = WSlugActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugIdentitiesRoute = WSlugIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugPeopleRoute = WSlugPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugReviewRoute = WSlugReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsRoute = WSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSourcesRoute = WSlugSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugIdentitiesIndexRoute = WSlugIdentitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugIdentitiesRoute,
} as any)
const WSlugIdentitiesIdentityIdRoute =
  WSlugIdentitiesIdentityIdRouteImport.update({
    id: '/$identityId',
    path: '/$identityId',
    getParentRoute: () => WSlugIdentitiesRoute,
  } as any)
const WSlugSourcesIndexRoute = WSlugSourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugSourcesRoute,
} as any)
const WSlugSourcesSourceIdRoute = WSlugSourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => WSlugSourcesRoute,
} as any)
const WSlugSourcesNewRoute = WSlugSourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WSlugSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$slug/activity': typeof WSlugActivityRoute
  '/w/$slug/identities': typeof WSlugIdentitiesRouteWithChildren
  '/w/$slug/people': typeof WSlugPeopleRoute
  '/w/$slug/review': typeof WSlugReviewRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/sources': typeof WSlugSourcesRouteWithChildren
  '/w/$slug/identities/$identityId': typeof WSlugIdentitiesIdentityIdRoute
  '/w/$slug/sources/$sourceId': typeof WSlugSourcesSourceIdRoute
  '/w/$slug/sources/new': typeof WSlugSourcesNewRoute
  '/w/$slug/identities/': typeof WSlugIdentitiesIndexRoute
  '/w/$slug/sources/': typeof WSlugSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$slug/activity': typeof WSlugActivityRoute
  '/w/$slug/people': typeof WSlugPeopleRoute
  '/w/$slug/review': typeof WSlugReviewRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/identities/$identityId': typeof WSlugIdentitiesIdentityIdRoute
  '/w/$slug/sources/$sourceId': typeof WSlugSourcesSourceIdRoute
  '/w/$slug/sources/new': typeof WSlugSourcesNewRoute
  '/w/$slug/identities': typeof WSlugIdentitiesIndexRoute
  '/w/$slug/sources': typeof WSlugSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$slug/activity': typeof WSlugActivityRoute
  '/w/$slug/identities': typeof WSlugIdentitiesRouteWithChildren
  '/w/$slug/people': typeof WSlugPeopleRoute
  '/w/$slug/review': typeof WSlugReviewRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/sources': typeof WSlugSourcesRouteWithChildren
  '/w/$slug/identities/$identityId': typeof WSlugIdentitiesIdentityIdRoute
  '/w/$slug/sources/$sourceId': typeof WSlugSourcesSourceIdRoute
  '/w/$slug/sources/new': typeof WSlugSourcesNewRoute
  '/w/$slug/identities/': typeof WSlugIdentitiesIndexRoute
  '/w/$slug/sources/': typeof WSlugSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/invite/$token'
    | '/w/$slug'
    | '/api/auth/$'
    | '/w/$slug/activity'
    | '/w/$slug/identities'
    | '/w/$slug/people'
    | '/w/$slug/review'
    | '/w/$slug/settings'
    | '/w/$slug/sources'
    | '/w/$slug/identities/$identityId'
    | '/w/$slug/sources/$sourceId'
    | '/w/$slug/sources/new'
    | '/w/$slug/identities/'
    | '/w/$slug/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/invite/$token'
    | '/w/$slug'
    | '/api/auth/$'
    | '/w/$slug/activity'
    | '/w/$slug/people'
    | '/w/$slug/review'
    | '/w/$slug/settings'
    | '/w/$slug/identities/$identityId'
    | '/w/$slug/sources/$sourceId'
    | '/w/$slug/sources/new'
    | '/w/$slug/identities'
    | '/w/$slug/sources'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/invite/$token'
    | '/w/$slug'
    | '/api/auth/$'
    | '/w/$slug/activity'
    | '/w/$slug/identities'
    | '/w/$slug/people'
    | '/w/$slug/review'
    | '/w/$slug/settings'
    | '/w/$slug/sources'
    | '/w/$slug/identities/$identityId'
    | '/w/$slug/sources/$sourceId'
    | '/w/$slug/sources/new'
    | '/w/$slug/identities/'
    | '/w/$slug/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  InviteTokenRoute: typeof InviteTokenRoute
  WSlugRoute: typeof WSlugRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/activity': {
      id: '/w/$slug/activity'
      path: '/activity'
      fullPath: '/w/$slug/activity'
      preLoaderRoute: typeof WSlugActivityRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/identities': {
      id: '/w/$slug/identities'
      path: '/identities'
      fullPath: '/w/$slug/identities'
      preLoaderRoute: typeof WSlugIdentitiesRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/people': {
      id: '/w/$slug/people'
      path: '/people'
      fullPath: '/w/$slug/people'
      preLoaderRoute: typeof WSlugPeopleRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/review': {
      id: '/w/$slug/review'
      path: '/review'
      fullPath: '/w/$slug/review'
      preLoaderRoute: typeof WSlugReviewRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings': {
      id: '/w/$slug/settings'
      path: '/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof WSlugSettingsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/sources': {
      id: '/w/$slug/sources'
      path: '/sources'
      fullPath: '/w/$slug/sources'
      preLoaderRoute: typeof WSlugSourcesRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/identities/': {
      id: '/w/$slug/identities/'
      path: '/'
      fullPath: '/w/$slug/identities/'
      preLoaderRoute: typeof WSlugIdentitiesIndexRouteImport
      parentRoute: typeof WSlugIdentitiesRoute
    }
    '/w/$slug/identities/$identityId': {
      id: '/w/$slug/identities/$identityId'
      path: '/$identityId'
      fullPath: '/w/$slug/identities/$identityId'
      preLoaderRoute: typeof WSlugIdentitiesIdentityIdRouteImport
      parentRoute: typeof WSlugIdentitiesRoute
    }
    '/w/$slug/sources/': {
      id: '/w/$slug/sources/'
      path: '/'
      fullPath: '/w/$slug/sources/'
      preLoaderRoute: typeof WSlugSourcesIndexRouteImport
      parentRoute: typeof WSlugSourcesRoute
    }
    '/w/$slug/sources/$sourceId': {
      id: '/w/$slug/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/w/$slug/sources/$sourceId'
      preLoaderRoute: typeof WSlugSourcesSourceIdRouteImport
      parentRoute: typeof WSlugSourcesRoute
    }
    '/w/$slug/sources/new': {
      id: '/w/$slug/sources/new'
      path: '/new'
      fullPath: '/w/$slug/sources/new'
      preLoaderRoute: typeof WSlugSourcesNewRouteImport
      parentRoute: typeof WSlugSourcesRoute
    }
  }
}

interface WSlugIdentitiesRouteChildren {
  WSlugIdentitiesIdentityIdRoute: typeof WSlugIdentitiesIdentityIdRoute
  WSlugIdentitiesIndexRoute: typeof WSlugIdentitiesIndexRoute
}

const WSlugIdentitiesRouteChildren: WSlugIdentitiesRouteChildren = {
  WSlugIdentitiesIdentityIdRoute: WSlugIdentitiesIdentityIdRoute,
  WSlugIdentitiesIndexRoute: WSlugIdentitiesIndexRoute,
}

const WSlugIdentitiesRouteWithChildren = WSlugIdentitiesRoute._addFileChildren(
  WSlugIdentitiesRouteChildren,
)

interface WSlugSourcesRouteChildren {
  WSlugSourcesSourceIdRoute: typeof WSlugSourcesSourceIdRoute
  WSlugSourcesNewRoute: typeof WSlugSourcesNewRoute
  WSlugSourcesIndexRoute: typeof WSlugSourcesIndexRoute
}

const WSlugSourcesRouteChildren: WSlugSourcesRouteChildren = {
  WSlugSourcesSourceIdRoute: WSlugSourcesSourceIdRoute,
  WSlugSourcesNewRoute: WSlugSourcesNewRoute,
  WSlugSourcesIndexRoute: WSlugSourcesIndexRoute,
}

const WSlugSourcesRouteWithChildren = WSlugSourcesRoute._addFileChildren(
  WSlugSourcesRouteChildren,
)

interface WSlugRouteChildren {
  WSlugActivityRoute: typeof WSlugActivityRoute
  WSlugIdentitiesRoute: typeof WSlugIdentitiesRouteWithChildren
  WSlugPeopleRoute: typeof WSlugPeopleRoute
  WSlugReviewRoute: typeof WSlugReviewRoute
  WSlugSettingsRoute: typeof WSlugSettingsRoute
  WSlugSourcesRoute: typeof WSlugSourcesRouteWithChildren
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugActivityRoute: WSlugActivityRoute,
  WSlugIdentitiesRoute: WSlugIdentitiesRouteWithChildren,
  WSlugPeopleRoute: WSlugPeopleRoute,
  WSlugReviewRoute: WSlugReviewRoute,
  WSlugSettingsRoute: WSlugSettingsRoute,
  WSlugSourcesRoute: WSlugSourcesRouteWithChildren,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  InviteTokenRoute: InviteTokenRoute,
  WSlugRoute: WSlugRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
