/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as ActivityRouteImport } from './app/activity'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as IdentitiesRouteImport } from './app/identities'
import { Route as ReviewRouteImport } from './app/review'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as SourcesRouteImport } from './app/sources'
import { Route as IdentitiesIndexRouteImport } from './app/identities/index'
import { Route as IdentitiesIdentityIdRouteImport } from './app/identities/$identityId'
import { Route as SourcesIndexRouteImport } from './app/sources/index'
import { Route as SourcesSourceIdRouteImport } from './app/sources/$sourceId'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesRoute = IdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIndexRoute = IdentitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdentitiesRoute,
} as any)
const IdentitiesIdentityIdRoute = IdentitiesIdentityIdRouteImport.update({
  id: '/$identityId',
  path: '/$identityId',
  getParentRoute: () => IdentitiesRoute,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourcesRoute,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => SourcesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/identities': typeof IdentitiesRouteWithChildren
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRouteWithChildren
  '/identities/$identityId': typeof IdentitiesIdentityIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/identities/': typeof IdentitiesIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/identities/$identityId': typeof IdentitiesIdentityIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/identities': typeof IdentitiesIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/identities': typeof IdentitiesRouteWithChildren
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRouteWithChildren
  '/identities/$identityId': typeof IdentitiesIdentityIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/identities/': typeof IdentitiesIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/identities'
    | '/review'
    | '/sign-in'
    | '/sources'
    | '/identities/$identityId'
    | '/sources/$sourceId'
    | '/identities/'
    | '/sources/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/review'
    | '/sign-in'
    | '/identities/$identityId'
    | '/sources/$sourceId'
    | '/identities'
    | '/sources'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/dashboard'
    | '/identities'
    | '/review'
    | '/sign-in'
    | '/sources'
    | '/identities/$identityId'
    | '/sources/$sourceId'
    | '/identities/'
    | '/sources/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DashboardRoute: typeof DashboardRoute
  IdentitiesRoute: typeof IdentitiesRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  SignInRoute: typeof SignInRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities': {
      id: '/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof IdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/': {
      id: '/identities/'
      path: '/'
      fullPath: '/identities/'
      preLoaderRoute: typeof IdentitiesIndexRouteImport
      parentRoute: typeof IdentitiesRoute
    }
    '/identities/$identityId': {
      id: '/identities/$identityId'
      path: '/$identityId'
      fullPath: '/identities/$identityId'
      preLoaderRoute: typeof IdentitiesIdentityIdRouteImport
      parentRoute: typeof IdentitiesRoute
    }
    '/sources/': {
      id: '/sources/'
      path: '/'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IdentitiesRouteChildren {
  IdentitiesIdentityIdRoute: typeof IdentitiesIdentityIdRoute
  IdentitiesIndexRoute: typeof IdentitiesIndexRoute
}

const IdentitiesRouteChildren: IdentitiesRouteChildren = {
  IdentitiesIdentityIdRoute: IdentitiesIdentityIdRoute,
  IdentitiesIndexRoute: IdentitiesIndexRoute,
}

const IdentitiesRouteWithChildren = IdentitiesRoute._addFileChildren(
  IdentitiesRouteChildren,
)

interface SourcesRouteChildren {
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DashboardRoute: DashboardRoute,
  IdentitiesRoute: IdentitiesRouteWithChildren,
  ReviewRoute: ReviewRoute,
  SignInRoute: SignInRoute,
  SourcesRoute: SourcesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
