/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as ArchivedProjectsRouteImport } from './app/archived-projects'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as InviteTokenRouteImport } from './app/invite.$token'
import { Route as PSlugRouteImport } from './app/p/$slug'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as PSlugAccountRouteImport } from './app/p/$slug/account'
import { Route as PSlugActivityRouteImport } from './app/p/$slug/activity'
import { Route as PSlugReviewRouteImport } from './app/p/$slug/review'
import { Route as PSlugSettingsRouteImport } from './app/p/$slug/settings'
import { Route as PSlugSourcesRouteImport } from './app/p/$slug/sources'
import { Route as PSlugSettingsIndexRouteImport } from './app/p/$slug/settings/index'
import { Route as PSlugSettingsIdentitiesRouteImport } from './app/p/$slug/settings/identities'
import { Route as PSlugSettingsPeopleRouteImport } from './app/p/$slug/settings/people'
import { Route as PSlugSettingsProjectRouteImport } from './app/p/$slug/settings/project'
import { Route as PSlugSourcesIndexRouteImport } from './app/p/$slug/sources/index'
import { Route as PSlugSourcesPathRouteImport } from './app/p/$slug/sources/$path'
import { Route as PSlugSourcesInspectRouteImport } from './app/p/$slug/sources/inspect'
import { Route as PSlugSourcesNewRouteImport } from './app/p/$slug/sources/new'
import { Route as PSlugSettingsIdentitiesIndexRouteImport } from './app/p/$slug/settings/identities/index'
import { Route as PSlugSettingsIdentitiesIdentityIdRouteImport } from './app/p/$slug/settings/identities/$identityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedProjectsRoute = ArchivedProjectsRouteImport.update({
  id: '/archived-projects',
  path: '/archived-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugAccountRoute = PSlugAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugActivityRoute = PSlugActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugReviewRoute = PSlugReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugSettingsRoute = PSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugSourcesRoute = PSlugSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugSettingsIndexRoute = PSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PSlugSettingsRoute,
} as any)
const PSlugSettingsIdentitiesRoute = PSlugSettingsIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => PSlugSettingsRoute,
} as any)
const PSlugSettingsPeopleRoute = PSlugSettingsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => PSlugSettingsRoute,
} as any)
const PSlugSettingsProjectRoute = PSlugSettingsProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => PSlugSettingsRoute,
} as any)
const PSlugSourcesIndexRoute = PSlugSourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PSlugSourcesRoute,
} as any)
const PSlugSourcesPathRoute = PSlugSourcesPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => PSlugSourcesRoute,
} as any)
const PSlugSourcesInspectRoute = PSlugSourcesInspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => PSlugSourcesRoute,
} as any)
const PSlugSourcesNewRoute = PSlugSourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PSlugSourcesRoute,
} as any)
const PSlugSettingsIdentitiesIndexRoute =
  PSlugSettingsIdentitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PSlugSettingsIdentitiesRoute,
  } as any)
const PSlugSettingsIdentitiesIdentityIdRoute =
  PSlugSettingsIdentitiesIdentityIdRouteImport.update({
    id: '/$identityId',
    path: '/$identityId',
    getParentRoute: () => PSlugSettingsIdentitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived-projects': typeof ArchivedProjectsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$slug/account': typeof PSlugAccountRoute
  '/p/$slug/activity': typeof PSlugActivityRoute
  '/p/$slug/review': typeof PSlugReviewRoute
  '/p/$slug/settings': typeof PSlugSettingsRouteWithChildren
  '/p/$slug/sources': typeof PSlugSourcesRouteWithChildren
  '/p/$slug/settings/identities': typeof PSlugSettingsIdentitiesRouteWithChildren
  '/p/$slug/settings/people': typeof PSlugSettingsPeopleRoute
  '/p/$slug/settings/project': typeof PSlugSettingsProjectRoute
  '/p/$slug/sources/$path': typeof PSlugSourcesPathRoute
  '/p/$slug/sources/inspect': typeof PSlugSourcesInspectRoute
  '/p/$slug/sources/new': typeof PSlugSourcesNewRoute
  '/p/$slug/settings/': typeof PSlugSettingsIndexRoute
  '/p/$slug/sources/': typeof PSlugSourcesIndexRoute
  '/p/$slug/settings/identities/$identityId': typeof PSlugSettingsIdentitiesIdentityIdRoute
  '/p/$slug/settings/identities/': typeof PSlugSettingsIdentitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived-projects': typeof ArchivedProjectsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$slug/account': typeof PSlugAccountRoute
  '/p/$slug/activity': typeof PSlugActivityRoute
  '/p/$slug/review': typeof PSlugReviewRoute
  '/p/$slug/settings/people': typeof PSlugSettingsPeopleRoute
  '/p/$slug/settings/project': typeof PSlugSettingsProjectRoute
  '/p/$slug/sources/$path': typeof PSlugSourcesPathRoute
  '/p/$slug/sources/inspect': typeof PSlugSourcesInspectRoute
  '/p/$slug/sources/new': typeof PSlugSourcesNewRoute
  '/p/$slug/settings': typeof PSlugSettingsIndexRoute
  '/p/$slug/sources': typeof PSlugSourcesIndexRoute
  '/p/$slug/settings/identities/$identityId': typeof PSlugSettingsIdentitiesIdentityIdRoute
  '/p/$slug/settings/identities': typeof PSlugSettingsIdentitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived-projects': typeof ArchivedProjectsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$slug/account': typeof PSlugAccountRoute
  '/p/$slug/activity': typeof PSlugActivityRoute
  '/p/$slug/review': typeof PSlugReviewRoute
  '/p/$slug/settings': typeof PSlugSettingsRouteWithChildren
  '/p/$slug/sources': typeof PSlugSourcesRouteWithChildren
  '/p/$slug/settings/identities': typeof PSlugSettingsIdentitiesRouteWithChildren
  '/p/$slug/settings/people': typeof PSlugSettingsPeopleRoute
  '/p/$slug/settings/project': typeof PSlugSettingsProjectRoute
  '/p/$slug/sources/$path': typeof PSlugSourcesPathRoute
  '/p/$slug/sources/inspect': typeof PSlugSourcesInspectRoute
  '/p/$slug/sources/new': typeof PSlugSourcesNewRoute
  '/p/$slug/settings/': typeof PSlugSettingsIndexRoute
  '/p/$slug/sources/': typeof PSlugSourcesIndexRoute
  '/p/$slug/settings/identities/$identityId': typeof PSlugSettingsIdentitiesIdentityIdRoute
  '/p/$slug/settings/identities/': typeof PSlugSettingsIdentitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived-projects'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/invite/$token'
    | '/p/$slug'
    | '/api/auth/$'
    | '/p/$slug/account'
    | '/p/$slug/activity'
    | '/p/$slug/review'
    | '/p/$slug/settings'
    | '/p/$slug/sources'
    | '/p/$slug/settings/identities'
    | '/p/$slug/settings/people'
    | '/p/$slug/settings/project'
    | '/p/$slug/sources/$path'
    | '/p/$slug/sources/inspect'
    | '/p/$slug/sources/new'
    | '/p/$slug/settings/'
    | '/p/$slug/sources/'
    | '/p/$slug/settings/identities/$identityId'
    | '/p/$slug/settings/identities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived-projects'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/invite/$token'
    | '/p/$slug'
    | '/api/auth/$'
    | '/p/$slug/account'
    | '/p/$slug/activity'
    | '/p/$slug/review'
    | '/p/$slug/settings/people'
    | '/p/$slug/settings/project'
    | '/p/$slug/sources/$path'
    | '/p/$slug/sources/inspect'
    | '/p/$slug/sources/new'
    | '/p/$slug/settings'
    | '/p/$slug/sources'
    | '/p/$slug/settings/identities/$identityId'
    | '/p/$slug/settings/identities'
  id:
    | '__root__'
    | '/'
    | '/archived-projects'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/invite/$token'
    | '/p/$slug'
    | '/api/auth/$'
    | '/p/$slug/account'
    | '/p/$slug/activity'
    | '/p/$slug/review'
    | '/p/$slug/settings'
    | '/p/$slug/sources'
    | '/p/$slug/settings/identities'
    | '/p/$slug/settings/people'
    | '/p/$slug/settings/project'
    | '/p/$slug/sources/$path'
    | '/p/$slug/sources/inspect'
    | '/p/$slug/sources/new'
    | '/p/$slug/settings/'
    | '/p/$slug/sources/'
    | '/p/$slug/settings/identities/$identityId'
    | '/p/$slug/settings/identities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedProjectsRoute: typeof ArchivedProjectsRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PSlugRoute: typeof PSlugRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived-projects': {
      id: '/archived-projects'
      path: '/archived-projects'
      fullPath: '/archived-projects'
      preLoaderRoute: typeof ArchivedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/account': {
      id: '/p/$slug/account'
      path: '/account'
      fullPath: '/p/$slug/account'
      preLoaderRoute: typeof PSlugAccountRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/activity': {
      id: '/p/$slug/activity'
      path: '/activity'
      fullPath: '/p/$slug/activity'
      preLoaderRoute: typeof PSlugActivityRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/review': {
      id: '/p/$slug/review'
      path: '/review'
      fullPath: '/p/$slug/review'
      preLoaderRoute: typeof PSlugReviewRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/settings': {
      id: '/p/$slug/settings'
      path: '/settings'
      fullPath: '/p/$slug/settings'
      preLoaderRoute: typeof PSlugSettingsRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/sources': {
      id: '/p/$slug/sources'
      path: '/sources'
      fullPath: '/p/$slug/sources'
      preLoaderRoute: typeof PSlugSourcesRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/settings/': {
      id: '/p/$slug/settings/'
      path: '/'
      fullPath: '/p/$slug/settings/'
      preLoaderRoute: typeof PSlugSettingsIndexRouteImport
      parentRoute: typeof PSlugSettingsRoute
    }
    '/p/$slug/settings/identities': {
      id: '/p/$slug/settings/identities'
      path: '/identities'
      fullPath: '/p/$slug/settings/identities'
      preLoaderRoute: typeof PSlugSettingsIdentitiesRouteImport
      parentRoute: typeof PSlugSettingsRoute
    }
    '/p/$slug/settings/people': {
      id: '/p/$slug/settings/people'
      path: '/people'
      fullPath: '/p/$slug/settings/people'
      preLoaderRoute: typeof PSlugSettingsPeopleRouteImport
      parentRoute: typeof PSlugSettingsRoute
    }
    '/p/$slug/settings/project': {
      id: '/p/$slug/settings/project'
      path: '/project'
      fullPath: '/p/$slug/settings/project'
      preLoaderRoute: typeof PSlugSettingsProjectRouteImport
      parentRoute: typeof PSlugSettingsRoute
    }
    '/p/$slug/sources/': {
      id: '/p/$slug/sources/'
      path: '/'
      fullPath: '/p/$slug/sources/'
      preLoaderRoute: typeof PSlugSourcesIndexRouteImport
      parentRoute: typeof PSlugSourcesRoute
    }
    '/p/$slug/sources/$path': {
      id: '/p/$slug/sources/$path'
      path: '/$path'
      fullPath: '/p/$slug/sources/$path'
      preLoaderRoute: typeof PSlugSourcesPathRouteImport
      parentRoute: typeof PSlugSourcesRoute
    }
    '/p/$slug/sources/inspect': {
      id: '/p/$slug/sources/inspect'
      path: '/inspect'
      fullPath: '/p/$slug/sources/inspect'
      preLoaderRoute: typeof PSlugSourcesInspectRouteImport
      parentRoute: typeof PSlugSourcesRoute
    }
    '/p/$slug/sources/new': {
      id: '/p/$slug/sources/new'
      path: '/new'
      fullPath: '/p/$slug/sources/new'
      preLoaderRoute: typeof PSlugSourcesNewRouteImport
      parentRoute: typeof PSlugSourcesRoute
    }
    '/p/$slug/settings/identities/': {
      id: '/p/$slug/settings/identities/'
      path: '/'
      fullPath: '/p/$slug/settings/identities/'
      preLoaderRoute: typeof PSlugSettingsIdentitiesIndexRouteImport
      parentRoute: typeof PSlugSettingsIdentitiesRoute
    }
    '/p/$slug/settings/identities/$identityId': {
      id: '/p/$slug/settings/identities/$identityId'
      path: '/$identityId'
      fullPath: '/p/$slug/settings/identities/$identityId'
      preLoaderRoute: typeof PSlugSettingsIdentitiesIdentityIdRouteImport
      parentRoute: typeof PSlugSettingsIdentitiesRoute
    }
  }
}

interface PSlugSettingsIdentitiesRouteChildren {
  PSlugSettingsIdentitiesIdentityIdRoute: typeof PSlugSettingsIdentitiesIdentityIdRoute
  PSlugSettingsIdentitiesIndexRoute: typeof PSlugSettingsIdentitiesIndexRoute
}

const PSlugSettingsIdentitiesRouteChildren: PSlugSettingsIdentitiesRouteChildren =
  {
    PSlugSettingsIdentitiesIdentityIdRoute:
      PSlugSettingsIdentitiesIdentityIdRoute,
    PSlugSettingsIdentitiesIndexRoute: PSlugSettingsIdentitiesIndexRoute,
  }

const PSlugSettingsIdentitiesRouteWithChildren =
  PSlugSettingsIdentitiesRoute._addFileChildren(
    PSlugSettingsIdentitiesRouteChildren,
  )

interface PSlugSettingsRouteChildren {
  PSlugSettingsIdentitiesRoute: typeof PSlugSettingsIdentitiesRouteWithChildren
  PSlugSettingsPeopleRoute: typeof PSlugSettingsPeopleRoute
  PSlugSettingsProjectRoute: typeof PSlugSettingsProjectRoute
  PSlugSettingsIndexRoute: typeof PSlugSettingsIndexRoute
}

const PSlugSettingsRouteChildren: PSlugSettingsRouteChildren = {
  PSlugSettingsIdentitiesRoute: PSlugSettingsIdentitiesRouteWithChildren,
  PSlugSettingsPeopleRoute: PSlugSettingsPeopleRoute,
  PSlugSettingsProjectRoute: PSlugSettingsProjectRoute,
  PSlugSettingsIndexRoute: PSlugSettingsIndexRoute,
}

const PSlugSettingsRouteWithChildren = PSlugSettingsRoute._addFileChildren(
  PSlugSettingsRouteChildren,
)

interface PSlugSourcesRouteChildren {
  PSlugSourcesPathRoute: typeof PSlugSourcesPathRoute
  PSlugSourcesInspectRoute: typeof PSlugSourcesInspectRoute
  PSlugSourcesNewRoute: typeof PSlugSourcesNewRoute
  PSlugSourcesIndexRoute: typeof PSlugSourcesIndexRoute
}

const PSlugSourcesRouteChildren: PSlugSourcesRouteChildren = {
  PSlugSourcesPathRoute: PSlugSourcesPathRoute,
  PSlugSourcesInspectRoute: PSlugSourcesInspectRoute,
  PSlugSourcesNewRoute: PSlugSourcesNewRoute,
  PSlugSourcesIndexRoute: PSlugSourcesIndexRoute,
}

const PSlugSourcesRouteWithChildren = PSlugSourcesRoute._addFileChildren(
  PSlugSourcesRouteChildren,
)

interface PSlugRouteChildren {
  PSlugAccountRoute: typeof PSlugAccountRoute
  PSlugActivityRoute: typeof PSlugActivityRoute
  PSlugReviewRoute: typeof PSlugReviewRoute
  PSlugSettingsRoute: typeof PSlugSettingsRouteWithChildren
  PSlugSourcesRoute: typeof PSlugSourcesRouteWithChildren
}

const PSlugRouteChildren: PSlugRouteChildren = {
  PSlugAccountRoute: PSlugAccountRoute,
  PSlugActivityRoute: PSlugActivityRoute,
  PSlugReviewRoute: PSlugReviewRoute,
  PSlugSettingsRoute: PSlugSettingsRouteWithChildren,
  PSlugSourcesRoute: PSlugSourcesRouteWithChildren,
}

const PSlugRouteWithChildren = PSlugRoute._addFileChildren(PSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedProjectsRoute: ArchivedProjectsRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  InviteTokenRoute: InviteTokenRoute,
  PSlugRoute: PSlugRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
